on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: setup
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'

      - name: create csproj
        run: >
          find . -name '.diralive' 2>/dev/null | xargs dirname
  